services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: frida
      POSTGRES_USER: frida
      POSTGRES_PASSWORD: frida
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U frida -d frida" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
