[package]
name = "frida_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
actix-web.workspace = true
async-trait.workspace = true
serde.workspace = true
chrono.workspace = true
serde_json.workspace = true
tokio.workspace = true
log.workspace = true