!include ../../config/dev.yaml

common:
  database_url: postgresql://postgres:postgres@0.0.0.0:5432/frida_test


importer:
  project_name: frida_ecom
  database_url: postgresql://postgres:postgres@0.0.0.0:5432/frida_test